#!/usr/bin/env python3
"""
Quick Setup Script for NCAA Basketball Model
Configures API keys and verifies credentials
"""

import os
import json

print("="*70)
print("NCAA BASKETBALL MODEL - QUICK SETUP")
print("="*70)

# Check 1: Verify KenPom data exists
print("\n📊 STEP 1: Checking KenPom Data")
kenpom_dir = "backend/data/raw/ncaab"
if os.path.exists(kenpom_dir):
    csv_files = [f for f in os.listdir(kenpom_dir) if f.endswith('.csv')]
    if csv_files:
        latest_csv = max(csv_files)
        print(f"   ✅ Found KenPom data: {latest_csv}")
    else:
        print(f"   ⚠️  No CSV files in {kenpom_dir}")
else:
    print(f"   ⚠️  Directory not found: {kenpom_dir}")

# Check 2: Configure Odds API Key
print("\n🔑 STEP 2: Configuring Odds API Key")
odds_api_key = "3b91452fcbaa6deffecb2e5843655099"
print(f"   ✅ Odds API Key: {odds_api_key[:10]}...{odds_api_key[-10:]}")

# Check 3: Find Google credentials
print("\n☁️  STEP 3: Locating Google Credentials")
credential_paths = [
    "google_sheets/credentials/service-account-key.json",
    "../google_sheets/credentials/service-account-key.json",
    "../../google_sheets/credentials/service-account-key.json",
]

credentials_found = False
credentials_path = None

for path in credential_paths:
    if os.path.exists(path):
        credentials_found = True
        credentials_path = path
        print(f"   ✅ Found credentials: {path}")
        
        # Try to read service account email
        try:
            with open(path, 'r') as f:
                creds = json.load(f)
                service_email = creds.get('client_email', 'Unknown')
                print(f"   📧 Service Account: {service_email}")
        except:
            print(f"   ⚠️  Could not read email from credentials")
        break

if not credentials_found:
    print(f"   ⚠️  Credentials not found in expected locations")
    print(f"   💡 Copy from your NBA/NFL project to: google_sheets/credentials/")

# Check 4: Get Sheet ID
print("\n📋 STEP 4: Google Sheet Configuration")
print("   ❓ Do you have a Google Sheet ID for NCAA Basketball?")
print("")
sheet_id = input("   Enter Sheet ID (or press Enter to skip): ").strip()

if sheet_id:
    print(f"   ✅ Sheet ID: {sheet_id[:20]}...")
else:
    print("   ⚠️  No Sheet ID provided")
    print("   💡 Follow the setup guide to create a sheet and get the ID")

# Create config file
print("\n⚙️  STEP 5: Creating Configuration File")

config_content = f'''"""
NCAA Basketball Model Configuration
Auto-generated by setup script
"""

# Odds API Configuration
ODDS_API_KEY = "{odds_api_key}"
ODDS_API_SPORT = "basketball_ncaab"  # NCAA Basketball

# Google Sheets Configuration
GOOGLE_CREDENTIALS_PATH = "{credentials_path if credentials_path else 'google_sheets/credentials/service-account-key.json'}"
GOOGLE_SHEET_ID = "{sheet_id if sheet_id else 'YOUR_SHEET_ID_HERE'}"  # Replace with your actual sheet ID

# Data Paths
KENPOM_DATA_DIR = "backend/data/raw/ncaab"
PREDICTIONS_OUTPUT_DIR = "backend/data/predictions"
TRACKING_DIR = "backend/data/tracking"

# Model Parameters
HOME_COURT_ADVANTAGE = 3.5  # Points (larger than NBA's 2.5)
LEAGUE_AVG_EFFICIENCY = 105.0  # Points per 100 possessions

# Confidence Thresholds
HIGH_CONFIDENCE_EDGE = 5.0  # 5+ point edge
MEDIUM_CONFIDENCE_EDGE = 3.0  # 3-5 point edge
LOW_CONFIDENCE_EDGE = 1.5  # 1.5-3 point edge
'''

# Save config to both locations
config_locations = ["config.py", "backend/config.py"]

for location in config_locations:
    os.makedirs(os.path.dirname(location) if os.path.dirname(location) else ".", exist_ok=True)
    with open(location, 'w') as f:
        f.write(config_content)
    print(f"   ✅ Created: {location}")

# Summary
print("\n" + "="*70)
print("SETUP SUMMARY")
print("="*70)

checks = [
    ("KenPom Data", os.path.exists(kenpom_dir) and csv_files),
    ("Odds API Key", True),
    ("Google Credentials", credentials_found),
    ("Google Sheet ID", bool(sheet_id)),
]

for name, status in checks:
    symbol = "✅" if status else "⚠️"
    print(f"   {symbol} {name}")

print("\n" + "="*70)

if all(status for _, status in checks):
    print("🎉 SETUP COMPLETE! Ready to run predictions.")
    print("\nNext step:")
    print("   python run_ncaab_predictions.py")
else:
    print("⚠️  SETUP INCOMPLETE - Please complete the following:")
    
    if not checks[0][1]:
        print("   1. Run KenPom scraper: python backend/scrapers/ncaab/kenpom_scraper_selenium.py")
    
    if not checks[2][1]:
        print("   2. Copy Google credentials from NBA/NFL project to: google_sheets/credentials/")
    
    if not checks[3][1]:
        print("   3. Create Google Sheet and get Sheet ID")
        print("      Follow: GOOGLE_SHEETS_SETUP.py for detailed instructions")
        print("      Then re-run: python setup_ncaab.py")

print("="*70)
